# Generated by Django 4.2.6 on 2025-02-18 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objects',
            options={'verbose_name': 'Object', 'verbose_name_plural': 'Objects'},
        ),
    ]
