# Generated by Django 3.2.25 on 2025-02-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='discrmatr',
            constraint=models.UniqueConstraint(fields=('user', 'discr_object'), name='unique_field1_field2'),
        ),
    ]
